### ISSUE TITLE
how i can wget v075 or v050 posenet?

### ISSUE THREAD

**Issue by qidiso** [infocom-tpo/PoseNet-CoreML#3]
when i use wget .py ,i can getposenet/mobilenet_v1_100/
but i want the version posenet/mobilenet_v1_075/ ,so i modified the wget.py .but i can not the download the MobilenetV1_partheat_1_biases , maybe the manifest.json need to modify too.
pls u give me the manifest.json of the v1_075 or v1_050 ,thank u very much.my email is 4975644@qq.com

**Comment by mbotsu** [comment]
Hi.
Modified model v1_075.
I have not checked v1_050 yet but it probably works.
Thank.

commit: https://github.com/infocom-tpo/PoseNet-CoreML/commit/145e175175cc2b599827b5812869bacdc839288e

**Comment by qidiso** [comment]
thank u ! i get it
